### ISSUE TITLE
weixin

### ISSUE THREAD

**Issue by happypeter** [happypeter/hen#2]
http://toy.haoduoshipin.com/weixin

```
20150506
xxxxx my story
```

转换成

``` html
<div class="card" id="20150506">
   my story
</div>
```

同时

``` css
.card:before {
  background: url("20150506.jpg")
}
```
